language: node_js
node_js:
- '5'
before_script:
- npm install -g gulp
script: npm run build:prod
branches:
  only:
  - deploy
deploy:
  provider: heroku
  api_key:
    secure: V+vsmFCBdMFAzRo2Zv6XLFMSPLmJIwQwXWRl0BAtulFpUkqw823I2ndJc2dE2CalV7Z6mqBy3OzaJh1L2VE8bWWNUCQ+LT5A07+gUoYFQTNNN5sVrxoetdR7TV53qLxoDI1N6k/+a8ZJWk6bOZ9C9iet94Sx8fnYfqTuYb4HI+voWul//T8wUEGBSw8JqFIXNuxMICwgAYvDyNoQNJLMojki91GNblVpomv/mbGsNBOAj/OxwdEz1vR5oQVddrjuCQASEaWH961hUNMpBImQL7osgFIZEbEqLpKAgXt/XuoLEzZ0eWXEXTQNoA0MJ22z/5by4cCNMNMT2BpIKkXMOivfChDAd+zJNBaJLmVWJgOX9jJq9z/lIVrNq96ESk3phuIFR1uP6yAR6piSI5cyU3jkhuukEHLyzKPTryZnj6zoKcWViru5HwqtBH8gtxTSVWoIW927+/lrDVGtLviYNBVBx+uemGHucYkPhbW7DbIKa5kgIEYxAJYSyuRj6Lo1BoMN0r2JaOMileApba5bHNZUwQOAr1bl/8Y8TIJgoaONDTaBSvRkQ3v965sL2NDSrV2vsuKxw2wzUaYlMyc9rmyc9qLbrNRGy3YEVbmDWjhJU9/KBEZX18AWJmE+g4eEflUQh8vnHxoBA6xOMzT3G4GHi2BhlKmrkcFhC6le6cE=
  app: cdp-ci
  skip_cleanup: true
  on: deploy
